<?php
// Set the content type to JSON
header("content-type: application/json");

// Include the configuration file
require("config.php");

// Get the HTTP request method
$method = $_SERVER["REQUEST_METHOD"];

// Handle the request based on the method
switch ($method) {
    case "GET":
            // Fetch all orders
                    $result = $Connection->query("SELECT * FROM orders");
                            if ($result) {
                                        echo json_encode($result->fetch_all(MYSQLI_ASSOC));
                                                } else {
                                                            http_response_code(500);
                                                                        echo json_encode(["status" => "error", "message" => "Failed to fetch orders"]);
                                                                                }
                                                                                        break;

                                                                                            case "POST":
                                                                                                    // Insert a new product
                                                                                                            $data = json_decode(file_get_contents("php://input"), true);
                                                                                                                    $name = $data["name"] ?? null;
                                                                                                                            $price = $data["price"] ?? null;
                                                                                                                                    $description = $data["description"] ?? null;
                                                                                                                                            $id = $data["id"] ?? null;

                                                                                                                                                    if ($name && $price && $description) {
                                                                                                                                                                $stmt = $Connection->prepare("INSERT INTO products (id, name, price, description) VALUES (?, ?, ?, ?)");
                                                                                                                                                                            $stmt->bind_param("ssds", $id, $name, $price, $description);
                                                                                                                                                                                        if ($stmt->execute()) {
                                                                                                                                                                                                        http_response_code(201);
                                                                                                                                                                                                                        echo json_encode(["status" => "success", "message" => "Posted"]);
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                    http_response_code(500);
                                                                                                                                                                                                                                                                    echo json_encode(["status" => "error", "message" => "Failed to post"]);
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                    http_response_code(400);
                                                                                                                                                                                                                                                                                                                echo json_encode(["status" => "error", "message" => "Invalid data"]);
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                    case "PUT":
                                                                                                                                                                                                                                                                                                                                            // Update a product
                                                                                                                                                                                                                                                                                                                                                    $id = $_GET["id"] ?? null;
                                                                                                                                                                                                                                                                                                                                                            $data = json_decode(file_get_contents("php://input"), true);
                                                                                                                                                                                                                                                                                                                                                                    $name = $data["name"] ?? null;
                                                                                                                                                                                                                                                                                                                                                                            $price = $data["price"] ?? null;
                                                                                                                                                                                                                                                                                                                                                                                    $description = $data["description"] ?? null;

                                                                                                                                                                                                                                                                                                                                                                                            if ($id && $name && $price && $description) {
                                                                                                                                                                                                                                                                                                                                                                                                        $stmt = $Connection->prepare("UPDATE products SET name=?, price=?, description=? WHERE id=?");
                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->bind_param("sdsi", $name, $price, $description, $id);
                                                                                                                                                                                                                                                                                                                                                                                                                                if ($stmt->execute()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                echo json_encode(["status" => "success", "message" => "Updated"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            http_response_code(500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo json_encode(["status" => "error", "message" => "Failed to update"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            http_response_code(400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo json_encode(["status" => "error", "message" => "Invalid data"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "DELETE":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Delete a product
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $id = $_GET["id"] ?? null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt = $Connection->prepare("DELETE FROM products WHERE id=?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->bind_param("i", $id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($stmt->execute()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo json_encode(["status" => "success", "message" => "DELETED"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    http_response_code(500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo json_encode(["status" => "error", "message" => "Failed to delete"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    http_response_code(400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo json_encode(["status" => "error", "message" => "No id provided"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Handle undefined request methods
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    http_response_code(400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo json_encode(["message" => "Undefined request method"]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>